jobs:
- job: Run_package
  Pool:
   name: Hosted windows 2019 with vs 2019
  steps:
  - task: Powershell@2
    display Name: Delta Execute
    inputs:
      filePath: '.Delta.Ps1\'
  - task: ArchiveFile@2
    displayName: Archive deltafiles
    inputs:
      rootFolderFile: 'deltacode'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'deltacode_$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: ArchiveFiles@2
    displayName: Archive deployfiles
    inputs:
      rootFolderOrFile: 'deploy'
      includeRootFolder: false
      archivetype:'zip'
      archiveFile: 'deploy_$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task:PublishBuildArtifacts@1
    displayname: 'Publish Artifact: delta'
    inputs:
      PathtoPublish:'deltacode_$(Build.BuildId).zip'
      ArtiFactName: 'deltacode_artifact'
      publishLocations: 'container'
  - task: PublishBuildArtifacts@1
    displayName: 'PublishArtifact:deploy'
    inputs:
      PathtoPublish:'deploy_$(Build.BuildId).zip'
      ArtifactName: 'deploy_artifact'
      publishLocation:'container'
  - task: Ant@1
    displayName: Ant Deploy check
    inputs:
      buildFile: 'deploy\build.xml'
      options: '-Dsf.password-$(sf.password)-Dsf.username-$(sf.username)-Dsf.serverurl-$(sf.serverurl)-Dsf.maxPoll-$(sf.maxPoll)'
      targets: $(targetname)
      publishJUnitResults: false
      javaHomeOption: 'JDKversion'
 